# Generated by Django 5.2.14 on 2026-08-18 02:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_seed_cliente_publico_general'),
        ('fiscal', '0007_clave_unidad_prod_serv_sat_initial'),
        ('inventario', '0003_devolucion_choice'),
        ('products', '0008_almacen_tipo_y_traspaso_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de venta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='products.almacen', verbose_name='Sucursal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='fiscal.formapago', verbose_name='Forma de pago')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha de devolución')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta', verbose_name='Venta original')),
            ],
            options={
                'verbose_name': 'Devolución de cliente',
                'verbose_name_plural': 'Devoluciones de cliente',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento (%)')),
                ('estrategia_salida', models.CharField(choices=[('fifo', 'FIFO (primero en entrar, primero en salir)'), ('fefo', 'FEFO (primero en caducar, primero en salir)')], default='fifo', max_length=10, verbose_name='Estrategia de salida')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='products.producto', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
            },
        ),
        migrations.CreateModel(
            name='DevolucionClienteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad devuelta')),
                ('reingresa_a_inventario', models.BooleanField(default=True, help_text='Si no aplica, el producto se da de baja como merma en lugar de regresar a stock.', verbose_name='Reingresa a inventario')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucioncliente', verbose_name='Devolución')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.ventadetalle', verbose_name='Línea de venta original')),
            ],
            options={
                'verbose_name': 'Detalle de devolución',
                'verbose_name_plural': 'Detalles de devolución',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalleLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad tomada')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo unitario al momento de la venta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='ventas.ventadetalle', verbose_name='Detalle de venta')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.lote', verbose_name='Lote de origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de venta',
                'verbose_name_plural': 'Lotes de venta',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente'], name='ventas_vent_cliente_1869ce_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['almacen'], name='ventas_vent_almacen_d280cc_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_venta'], name='ventas_vent_fecha_v_357f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucioncliente',
            index=models.Index(fields=['venta'], name='ventas_devo_venta_i_173618_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetalle',
            index=models.Index(fields=['venta'], name='ventas_vent_venta_i_b7bd49_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetalle',
            index=models.Index(fields=['producto'], name='ventas_vent_product_b27911_idx'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='vtd_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='vtd_precio_unitario_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0), ('descuento__lte', 100)), name='vtd_descuento_rango_valido'),
        ),
        migrations.AddIndex(
            model_name='devolucionclientedetalle',
            index=models.Index(fields=['devolucion'], name='ventas_devo_devoluc_a6b909_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionclientedetalle',
            index=models.Index(fields=['venta_detalle'], name='ventas_devo_venta_d_73074d_idx'),
        ),
        migrations.AddConstraint(
            model_name='devolucionclientedetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='dvd_cantidad_positiva'),
        ),
        migrations.AddIndex(
            model_name='ventadetallelote',
            index=models.Index(fields=['detalle'], name='ventas_vent_detalle_5060d3_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetallelote',
            index=models.Index(fields=['lote'], name='ventas_vent_lote_id_8fa900_idx'),
        ),
        migrations.AddConstraint(
            model_name='ventadetallelote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='vtl_cantidad_positiva'),
        ),
    ]
