# Generated by Django 5.2.14 on 2026-09-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_retarget_user_fk_to_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='veces_impreso',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Se incrementa cada vez que se abre el ticket para imprimirlo o reimprimirlo.', verbose_name='Veces impreso'),
        ),
    ]
