# Generated by Django 5.2.14 on 2026-09-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_producto_volumen_and_more'),
        ('ventas', '0003_venta_veces_impreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='El turno propio y abierto del usuario que cobró, tomado automáticamente (ver ventas.services.obtener_turno_abierto). No lo elige el usuario.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='products.turno', verbose_name='Turno'),
        ),
    ]
