# Generated by Django 5.2.14 on 2026-09-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_producto_volumen_and_more'),
        ('ventas', '0004_venta_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='lista_precio',
            field=models.ForeignKey(blank=True, help_text='De qué lista salió el precio_unitario capturado -no se usa para calcularlo, solo se registra para reportes como la comisión por colaborador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.listaprecio', verbose_name='Lista de precio'),
        ),
    ]
