# Generated by Django 5.2.14 on 2026-09-17 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0009_renombrar_forma_pago_17'),
        ('ventas', '0005_ventadetalle_lista_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.ForeignKey(blank=True, help_text='Vacío cuando el cobro se dividió en varias formas de pago (ver Venta.pagos).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='fiscal.formapago', verbose_name='Forma de pago'),
        ),
        migrations.CreateModel(
            name='VentaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_venta', to='fiscal.formapago', verbose_name='Forma de pago')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago de venta',
                'verbose_name_plural': 'Pagos de venta',
                'indexes': [models.Index(fields=['venta'], name='ventas_vent_venta_i_1d20b7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='vtp_monto_positivo')],
            },
        ),
    ]
