# Generated by Django 5.2.14 on 2026-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_venta_forma_pago_ventapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='efectivo_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo cuando forma_pago es Efectivo; de aquí sale Venta.cambio.', max_digits=12, null=True, verbose_name='Efectivo recibido'),
        ),
        migrations.AddField(
            model_name='venta',
            name='referencia_pago',
            field=models.CharField(blank=True, help_text='Solo cuando el cobro no se dividió (ver VentaPago.referencia para el caso dividido).', max_length=50, verbose_name='Referencia de pago'),
        ),
        migrations.AddField(
            model_name='ventapago',
            name='recibido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo cuando forma_pago es Efectivo; de aquí sale VentaPago.cambio.', max_digits=12, null=True, verbose_name='Efectivo recibido'),
        ),
        migrations.AddField(
            model_name='ventapago',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Referencia de pago'),
        ),
    ]
