# Generated by Django 5.2.14 on 2026-09-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_almacen_puntoventa_numero'),
        ('ventas', '0007_venta_efectivo_recibido_venta_referencia_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='El turno propio y abierto del usuario que cobró, tomado automáticamente (ver products.services.turno_abierto_de); de ahí también sale la sucursal de la venta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='products.turno', verbose_name='Turno'),
        ),
    ]
