# Generated by Django 5.2.14 on 2026-10-01 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_facturaglobal'),
        ('ventas', '0008_alter_venta_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='factura_global',
            field=models.ForeignKey(blank=True, help_text='Venta a Público en general ya incluida en el cierre fiscal del turno (ver facturacion.FacturaGlobal); vacío si todavía no se cierra el turno o si el cliente pidió su propia factura (ver Venta.factura).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='facturacion.facturaglobal', verbose_name='Factura global'),
        ),
    ]
