# Generated by Django 5.2.14 on 2026-10-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_venta_factura_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_remision',
            field=models.BooleanField(default=False, help_text='Sigue el mismo proceso que cualquier venta (descuenta inventario, se cobra igual), pero nunca tiene impacto fiscal: no se le genera factura individual ni entra a la factura global del turno, y se imprime como Nota de remisión en vez de ticket.', verbose_name='Es remisión'),
        ),
    ]
