# Generated by Django 5.2.14 on 2026-08-18 03:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_promocion_proveedor_initial'),
        ('fiscal', '0007_clave_unidad_prod_serv_sat_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_limite_pronto_pago', models.DateField(blank=True, null=True, verbose_name='Fecha límite para pronto pago')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago parcial'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10, verbose_name='Estatus')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('orden_compra', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_pagar', to='compras.ordencompra', verbose_name='Orden de compra')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta por pagar',
                'verbose_name_plural': 'Cuentas por pagar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto pagado')),
                ('aplica_descuento_pronto_pago', models.BooleanField(default=False, verbose_name='Aplica descuento por pronto pago')),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto de descuento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('cuenta_por_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pagos.cuentaporpagar', verbose_name='Cuenta por pagar')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proveedor', to='fiscal.formapago', verbose_name='Forma de pago')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a proveedor',
                'verbose_name_plural': 'Pagos a proveedores',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['estatus'], name='pagos_cuent_estatus_680c25_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['fecha_vencimiento'], name='pagos_cuent_fecha_v_f44cc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.CheckConstraint(condition=models.Q(('monto_total__gt', 0)), name='cxp_monto_total_positivo'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cuenta_por_pagar'], name='pagos_pago_cuenta__1ebf6a_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='pagos_pago_fecha_p_af939d_idx'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado__gt', 0)), name='pago_monto_pagado_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_descuento__gte', 0)), name='pago_monto_descuento_no_negativo'),
        ),
    ]
