# Generated by Django 5.2.14 on 2026-08-24 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/', verbose_name='Comprobante de pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_referencia',
            field=models.CharField(blank=True, help_text='Requerido cuando la forma de pago es cheque nominativo o compensación (nota de crédito).', max_length=50, verbose_name='Número de cheque o nota de crédito'),
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un %(model_name)s con este nombre.'}, max_length=100, unique=True, verbose_name='Nombre del banco')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='banco',
            field=models.ForeignKey(blank=True, help_text='Requerido cuando la forma de pago es transferencia.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagos.banco', verbose_name='Banco'),
        ),
    ]
