# Generated by Django 5.2.14 on 2026-09-03 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0009_renombrar_forma_pago_17'),
        ('pagos', '0004_alter_pago_banco'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('numero_referencia', models.CharField(blank=True, max_length=50, verbose_name='Número de cheque o nota de crédito')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibos_pago', to='pagos.banco', verbose_name='Banco')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos_pago', to='fiscal.formapago', verbose_name='Forma de pago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos_pago', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo de pago',
                'verbose_name_plural': 'Recibos de pago',
                'ordering': ['-numero'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='recibo',
            field=models.ForeignKey(blank=True, help_text='Agrupa este pago con los demás del mismo evento (ej. varias cuentas pagadas juntas).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagos.recibopago', verbose_name='Recibo de pago'),
        ),
        migrations.AddIndex(
            model_name='recibopago',
            index=models.Index(fields=['proveedor'], name='pagos_recib_proveed_8ef996_idx'),
        ),
        migrations.AddIndex(
            model_name='recibopago',
            index=models.Index(fields=['fecha_pago'], name='pagos_recib_fecha_p_d22148_idx'),
        ),
    ]
