# Generated by Django 5.2.14 on 2026-09-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_recibopago_pago_recibo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='banco',
            field=models.ForeignKey(blank=True, help_text='Requerido para transferencia; opcional para pago con cheque, tarjeta de crédito o débito.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagos.banco', verbose_name='Banco'),
        ),
    ]
