# Generated by Django 5.2.14 on 2026-10-02 11:12

import apps.core.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_alter_pago_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.archivos.RutaAleatoria('pagos/comprobantes'), verbose_name='Comprobante de pago'),
        ),
    ]
