# Generated by Django 5.2.14 on 2026-09-08 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0009_renombrar_forma_pago_17'),
        ('pagos', '0005_recibopago_pago_recibo_and_more'),
        ('ventas', '0002_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Cobro parcial'), ('cobrada', 'Cobrada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10, verbose_name='Estatus')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_cobrar', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por cobrar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_cobro', models.DateField(verbose_name='Fecha de cobro')),
                ('monto_cobrado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto cobrado')),
                ('numero_referencia', models.CharField(blank=True, help_text='Requerido cuando la forma de pago es cheque nominativo.', max_length=50, verbose_name='Número de cheque')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='cobros/comprobantes/', verbose_name='Comprobante de cobro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('banco', models.ForeignKey(blank=True, help_text='Requerido para transferencia; opcional para pago con tarjeta de crédito o débito.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='pagos.banco', verbose_name='Banco')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_cliente', to='fiscal.formapago', verbose_name='Forma de pago')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('cuenta_por_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='cobros.cuentaporcobrar', verbose_name='Cuenta por cobrar')),
            ],
            options={
                'verbose_name': 'Cobro a cliente',
                'verbose_name_plural': 'Cobros a clientes',
                'ordering': ['-fecha_cobro', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['estatus'], name='cobros_cuen_estatus_3f8c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['fecha_vencimiento'], name='cobros_cuen_fecha_v_2c18e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporcobrar',
            constraint=models.CheckConstraint(condition=models.Q(('monto_total__gt', 0)), name='cxc_monto_total_positivo'),
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['cuenta_por_cobrar'], name='cobros_cobr_cuenta__ab2976_idx'),
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['fecha_cobro'], name='cobros_cobr_fecha_c_c2aa69_idx'),
        ),
        migrations.AddConstraint(
            model_name='cobro',
            constraint=models.CheckConstraint(condition=models.Q(('monto_cobrado__gt', 0)), name='cobro_monto_cobrado_positivo'),
        ),
    ]
