# Generated by Django 5.2.14 on 2026-10-02 11:12

import apps.core.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.archivos.RutaAleatoria('cobros/comprobantes'), verbose_name='Comprobante de cobro'),
        ),
    ]
