# Generated by Django 5.2.14 on 2026-09-14 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0025_producto_volumen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionColaboradorLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comisión (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_ruta', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_ruta', to='products.linea', verbose_name='Línea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comisión por colaborador',
                'verbose_name_plural': 'Comisiones por colaborador',
                'ordering': ['colaborador__first_name', 'colaborador__username', 'linea__nombre'],
                'constraints': [models.UniqueConstraint(fields=('colaborador', 'linea'), name='ccl_unico_colaborador_linea'), models.CheckConstraint(condition=models.Q(('porcentaje__gte', 0), ('porcentaje__lte', 100)), name='ccl_porcentaje_rango_valido')],
            },
        ),
    ]
