# Generated by Django 5.2.14 on 2026-10-02 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioUnico',
            fields=[
                ('token', models.UUIDField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=255)),
                ('url_resultado', models.CharField(blank=True, max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío único de formulario',
                'verbose_name_plural': 'Envíos únicos de formulario',
            },
        ),
    ]
