# Generated by Django 5.2.14 on 2026-08-18 02:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_clave_unidad_prod_serv_sat_initial'),
        ('proveedores', '0001_proveedor_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descuento_pronto_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento por pronto pago (%)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_pronto_pago',
            field=models.PositiveIntegerField(default=0, help_text='Si el pago se hace dentro de estos días desde la orden, aplica el descuento por pronto pago.', verbose_name='Días para pronto pago'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_pronto_pago__gte', 0), ('descuento_pronto_pago__lte', 100)), name='proveedor_descuento_pronto_pago_rango_valido'),
        ),
    ]
