# Generated by Django 5.2.14 on 2026-08-18 06:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_seed_cliente_publico_general'),
        ('products', '0012_producto_impuestos'),
        ('ventas', '0001_venta_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_cotizacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de cotización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estatus', models.CharField(choices=[('abierta', 'Abierta'), ('convertida', 'Convertida a venta')], default='abierta', max_length=10, verbose_name='Estatus')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='products.almacen', verbose_name='Sucursal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='ventas.venta', verbose_name='Venta generada')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_cotizacion'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento (%)')),
                ('estrategia_salida', models.CharField(choices=[('fifo', 'FIFO (primero en entrar, primero en salir)'), ('fefo', 'FEFO (primero en caducar, primero en salir)')], default='fifo', max_length=10, verbose_name='Estrategia de salida')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizaciones.cotizacion', verbose_name='Cotización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='products.producto', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de cotización',
                'verbose_name_plural': 'Detalles de cotización',
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente'], name='cotizacione_cliente_b0cc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['almacen'], name='cotizacione_almacen_8d8bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estatus'], name='cotizacione_estatus_d55bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizaciondetalle',
            index=models.Index(fields=['cotizacion'], name='cotizacione_cotizac_cf2003_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizaciondetalle',
            index=models.Index(fields=['producto'], name='cotizacione_product_3ba733_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizaciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ctd_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='cotizaciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='ctd_precio_unitario_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cotizaciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0), ('descuento__lte', 100)), name='ctd_descuento_rango_valido'),
        ),
    ]
