# Generated by Django 5.2.14 on 2026-09-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_alter_cotizacion_punto_venta_numero_documento'),
        ('products', '0027_almacen_puntoventa_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='El turno propio y abierto de quien la levantó, tomado automáticamente (ver products.services.turno_abierto_de). No lo elige el usuario.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='products.turno', verbose_name='Turno'),
        ),
    ]
