# Generated by Django 5.2.14 on 2026-08-17 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_seed_regimen_fiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(error_messages={'unique': 'Ya existe un %(model_name)s con esta clave.'}, max_length=10, unique=True, verbose_name='Clave SAT')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('aplica_fisica', models.BooleanField(default=False, verbose_name='Aplica a persona física')),
                ('aplica_moral', models.BooleanField(default=False, verbose_name='Aplica a persona moral')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso CFDI',
                'verbose_name_plural': 'Usos CFDI',
                'ordering': ['clave'],
                'indexes': [models.Index(fields=['clave'], name='fiscal_usoc_clave_727771_idx')],
            },
        ),
    ]
