# Generated by Django 5.2.14 on 2026-08-17 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_seed_forma_pago_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveProdServSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(error_messages={'unique': 'Ya existe un %(model_name)s con esta clave.'}, max_length=10, unique=True, verbose_name='Clave SAT')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clave de producto o servicio SAT',
                'verbose_name_plural': 'Claves de producto o servicio SAT',
                'ordering': ['clave'],
                'indexes': [models.Index(fields=['clave'], name='fiscal_clav_clave_e0e4fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClaveUnidadSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(error_messages={'unique': 'Ya existe un %(model_name)s con esta clave.'}, max_length=10, unique=True, verbose_name='Clave SAT')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la unidad')),
                ('simbolo', models.CharField(blank=True, max_length=20, verbose_name='Símbolo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clave de unidad SAT',
                'verbose_name_plural': 'Claves de unidad SAT',
                'ordering': ['clave'],
                'indexes': [models.Index(fields=['clave'], name='fiscal_clav_clave_86a090_idx')],
            },
        ),
    ]
