# Generated by Django 5.2.14 on 2026-08-17 22:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_almacen_tipo_y_traspaso_choice'),
        ('products', '0008_almacen_tipo_y_traspaso_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_envio', models.DateField(verbose_name='Fecha de envío')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='borrador', max_length=10, verbose_name='Estatus')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_recibidos', to='products.almacen', verbose_name='Almacén destino')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_enviados', to='products.almacen', verbose_name='Almacén origen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traspaso',
                'verbose_name_plural': 'Traspasos',
                'ordering': ['-fecha_envio', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraspasoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad solicitada')),
                ('estrategia_salida', models.CharField(choices=[('fifo', 'FIFO (primero en entrar, primero en salir)'), ('fefo', 'FEFO (primero en caducar, primero en salir)')], default='fifo', max_length=10, verbose_name='Estrategia de salida')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_traspaso', to='products.producto', verbose_name='Producto')),
                ('traspaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='traspasos.traspaso', verbose_name='Traspaso')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de traspaso',
                'verbose_name_plural': 'Detalles de traspaso',
            },
        ),
        migrations.CreateModel(
            name='TraspasoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad transferida')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='traspasos.traspasodetalle', verbose_name='Detalle de traspaso')),
                ('lote_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspaso_origen', to='inventario.lote', verbose_name='Lote generado en destino')),
                ('lote_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_salida', to='inventario.lote', verbose_name='Lote de origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de traspaso',
                'verbose_name_plural': 'Lotes de traspaso',
            },
        ),
        migrations.AddIndex(
            model_name='traspaso',
            index=models.Index(fields=['almacen_origen'], name='traspasos_t_almacen_299267_idx'),
        ),
        migrations.AddIndex(
            model_name='traspaso',
            index=models.Index(fields=['almacen_destino'], name='traspasos_t_almacen_43d68b_idx'),
        ),
        migrations.AddIndex(
            model_name='traspaso',
            index=models.Index(fields=['estatus'], name='traspasos_t_estatus_28fefd_idx'),
        ),
        migrations.AddIndex(
            model_name='traspasodetalle',
            index=models.Index(fields=['traspaso'], name='traspasos_t_traspas_ba8653_idx'),
        ),
        migrations.AddIndex(
            model_name='traspasodetalle',
            index=models.Index(fields=['producto'], name='traspasos_t_product_3c41fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='traspasodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='trd_cantidad_positiva'),
        ),
        migrations.AddIndex(
            model_name='traspasolote',
            index=models.Index(fields=['detalle'], name='traspasos_t_detalle_23c2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='traspasolote',
            index=models.Index(fields=['lote_origen'], name='traspasos_t_lote_or_19e771_idx'),
        ),
        migrations.AddConstraint(
            model_name='traspasolote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='trl_cantidad_positiva'),
        ),
    ]
