# Generated by Django 5.2.14 on 2026-09-02 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0017_puntoventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('es_principal', models.BooleanField(default=True, help_text='La sucursal donde trabaja normalmente. Solo puede haber una principal por usuario.', verbose_name='Sucursal principal')),
                ('es_encargado', models.BooleanField(default=False, help_text='Supervisa al resto del personal de esta sucursal (sin poder de cancelar/autorizar, eso es exclusivo del Administrador).', verbose_name='Encargado de esta sucursal')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='products.almacen', verbose_name='Almacén')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_sucursal', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de sucursal',
                'verbose_name_plural': 'Asignaciones de sucursal',
                'ordering': ['usuario', '-es_principal'],
                'indexes': [models.Index(fields=['usuario'], name='accounts_as_usuario_d5511c_idx'), models.Index(fields=['almacen'], name='accounts_as_almacen_de2bb2_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'almacen'), name='asu_unico_usuario_almacen')],
            },
        ),
    ]
