# Generated by Django 5.2.14 on 2026-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_una_sucursal_principal'),
        ('products', '0029_almacen_tipo_movil'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacionsucursal',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('usuario',), name='asu_una_principal_por_usuario', violation_error_message='Este usuario ya tiene otra sucursal marcada como principal.'),
        ),
    ]
