# Generated by Django 5.2.14 on 2026-08-18 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0007_clave_unidad_prod_serv_sat_initial'),
        ('ventas', '0001_venta_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_persona', models.CharField(choices=[('fisica', 'Persona física'), ('moral', 'Persona moral')], max_length=10, verbose_name='Tipo de persona')),
                ('rfc', models.CharField(error_messages={'unique': 'Ya existe un %(model_name)s con este RFC.'}, max_length=13, unique=True, verbose_name='RFC')),
                ('nombre_fiscal', models.CharField(max_length=255, verbose_name='Nombre o razón social (fiscal)')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, verbose_name='Nombre comercial')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código postal (lugar de expedición)')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('serie_default', models.CharField(default='A', max_length=10, verbose_name='Serie de factura')),
                ('siguiente_folio', models.PositiveIntegerField(default=1, verbose_name='Siguiente folio a asignar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('regimen_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='fiscal.regimenfiscal', verbose_name='Régimen fiscal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos de la empresa',
                'verbose_name_plural': 'Datos de la empresa',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serie', models.CharField(max_length=10, verbose_name='Serie')),
                ('numero_folio', models.PositiveIntegerField(verbose_name='Folio')),
                ('moneda', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('lugar_expedicion', models.CharField(max_length=5, verbose_name='Lugar de expedición (código postal)')),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('timbrada', 'Timbrada'), ('cancelada', 'Cancelada'), ('error', 'Error al timbrar')], default='borrador', max_length=10, verbose_name='Estatus')),
                ('facturama_id', models.CharField(blank=True, max_length=100, verbose_name='Id en Facturama')),
                ('uuid_fiscal', models.CharField(blank=True, max_length=36, verbose_name='Folio fiscal (UUID)')),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de timbrado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='fiscal.metodopago', verbose_name='Método de pago')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uso_cfdi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='fiscal.usocfdi', verbose_name='Uso de CFDI')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estatus'], name='facturacion_estatus_422005_idx'), models.Index(fields=['uuid_fiscal'], name='facturacion_uuid_fi_faaabe_idx')],
                'constraints': [models.UniqueConstraint(fields=('serie', 'numero_folio'), name='unica_serie_folio')],
            },
        ),
    ]
