# Generated by Django 5.2.14 on 2026-10-01 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_retarget_user_fk_to_accounts'),
        ('fiscal', '0009_renombrar_forma_pago_17'),
        ('products', '0028_puntoventa_consecutivo_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serie', models.CharField(max_length=10, verbose_name='Serie')),
                ('numero_folio', models.PositiveIntegerField(verbose_name='Folio')),
                ('moneda', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('lugar_expedicion', models.CharField(max_length=5, verbose_name='Lugar de expedición (código postal)')),
                ('periodo_mes', models.CharField(max_length=2, verbose_name='Mes del periodo (SAT)')),
                ('periodo_anio', models.PositiveIntegerField(verbose_name='Año del periodo (SAT)')),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('timbrada', 'Timbrada'), ('cancelada', 'Cancelada'), ('error', 'Error al timbrar')], default='borrador', max_length=10, verbose_name='Estatus')),
                ('facturama_id', models.CharField(blank=True, max_length=100, verbose_name='Id en Facturama')),
                ('uuid_fiscal', models.CharField(blank=True, max_length=36, verbose_name='Folio fiscal (UUID)')),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de timbrado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_globales', to='fiscal.metodopago', verbose_name='Método de pago')),
                ('turno', models.OneToOneField(help_text='Un turno solo puede tener una factura global.', on_delete=django.db.models.deletion.PROTECT, related_name='factura_global', to='products.turno', verbose_name='Turno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura global',
                'verbose_name_plural': 'Facturas globales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estatus'], name='facturacion_estatus_6a473d_idx'), models.Index(fields=['uuid_fiscal'], name='facturacion_uuid_fi_598567_idx')],
                'constraints': [models.UniqueConstraint(fields=('serie', 'numero_folio'), name='unica_serie_folio_global')],
            },
        ),
    ]
