# Generated by Django 5.2.14 on 2026-10-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_facturaglobal'),
        ('fiscal', '0009_renombrar_forma_pago_17'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaglobal',
            name='forma_pago',
            field=models.ForeignKey(default=1, help_text='La forma de pago que acumuló el monto más alto entre las ventas concentradas aquí (mismo criterio que el sistema anterior); el SAT no admite "99 Por definir" combinado con método de pago PUE (pago ya recibido, nunca diferido).', on_delete=django.db.models.deletion.PROTECT, related_name='facturas_globales', to='fiscal.formapago', verbose_name='Forma de pago'),
            preserve_default=False,
        ),
    ]
