# Generated by Django 5.2.14 on 2026-10-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_facturaglobal_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='folio_facturama',
            field=models.CharField(blank=True, max_length=40, verbose_name='Folio asignado por Facturama'),
        ),
        migrations.AddField(
            model_name='factura',
            name='serie_facturama',
            field=models.CharField(blank=True, max_length=25, verbose_name='Serie asignada por Facturama'),
        ),
        migrations.AddField(
            model_name='facturaglobal',
            name='folio_facturama',
            field=models.CharField(blank=True, max_length=40, verbose_name='Folio asignado por Facturama'),
        ),
        migrations.AddField(
            model_name='facturaglobal',
            name='serie_facturama',
            field=models.CharField(blank=True, max_length=25, verbose_name='Serie asignada por Facturama'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estatus',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('timbrando', 'Timbrando'), ('timbrada', 'Timbrada'), ('cancelada', 'Cancelada'), ('error', 'Error al timbrar')], default='borrador', max_length=10, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='facturaglobal',
            name='estatus',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('timbrando', 'Timbrando'), ('timbrada', 'Timbrada'), ('cancelada', 'Cancelada'), ('error', 'Error al timbrar')], default='borrador', max_length=10, verbose_name='Estatus'),
        ),
    ]
