# Generated by Django 5.2.14 on 2026-08-18 01:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0007_clave_unidad_prod_serv_sat_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('tipo_persona', models.CharField(blank=True, choices=[('fisica', 'Persona física'), ('moral', 'Persona moral')], max_length=10, verbose_name='Tipo de persona')),
                ('rfc', models.CharField(blank=True, error_messages={'unique': 'Ya existe un %(model_name)s con este RFC.'}, max_length=13, null=True, unique=True, verbose_name='RFC')),
                ('nombre_fiscal', models.CharField(blank=True, max_length=255, verbose_name='Nombre o razón social (fiscal)')),
                ('codigo_postal', models.CharField(blank=True, max_length=5, verbose_name='Código postal fiscal')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('tiene_credito', models.BooleanField(default=False, verbose_name='Crédito autorizado')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Límite de crédito')),
                ('dias_credito', models.PositiveIntegerField(default=0, verbose_name='Días de crédito')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('regimen_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='fiscal.regimenfiscal', verbose_name='Régimen fiscal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uso_cfdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='fiscal.usocfdi', verbose_name='Uso de CFDI')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='clientes_cl_nombre_c231de_idx'), models.Index(fields=['rfc'], name='clientes_cl_rfc_3080e6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('descuento__gte', 0), ('descuento__lte', 100)), name='cliente_descuento_rango_valido'), models.CheckConstraint(condition=models.Q(('limite_credito__gte', 0)), name='cliente_limite_credito_no_negativo')],
            },
        ),
    ]
