# Generated by Django 5.2.14 on 2026-08-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_retarget_user_fk_to_accounts'),
        ('products', '0014_listaprecio_productoprecio_producto_codigo_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lista_precio',
            field=models.ForeignKey(blank=True, help_text='Lista de precios que se aplica por defecto a este cliente en ventas y cotizaciones.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='products.listaprecio', verbose_name='Lista de precios'),
        ),
    ]
