# Generated by Django 5.2.14 on 2026-09-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_lista_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, help_text='Se muestra en el ticket de venta impreso.', max_length=255, verbose_name='Dirección'),
        ),
    ]
