# Generated by Django 5.2.14 on 2026-10-01 06:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_cliente_direccion'),
        ('inventario', '0008_alter_movimientoinventario_tipo'),
        ('products', '0028_puntoventa_consecutivo_pedido'),
        ('ventas', '0008_alter_venta_turno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_documento', models.CharField(editable=False, help_text='Folio para el cliente: número de almacén + número de punto de venta + "P" + consecutivo. Se genera solo al guardar y no se puede editar.', max_length=20, unique=True, verbose_name='Número de pedido')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pedido')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estatus', models.CharField(choices=[('abierto', 'Abierto'), ('convertido', 'Convertido a venta'), ('cancelado', 'Cancelado')], default='abierto', max_length=10, verbose_name='Estatus')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255, verbose_name='Motivo de cancelación')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='products.almacen', verbose_name='Sucursal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='products.puntoventa', verbose_name='Punto de venta')),
                ('turno', models.ForeignKey(blank=True, help_text='El turno propio y abierto de quien lo levantó, tomado automáticamente (ver products.services.turno_abierto_de). No lo elige el usuario.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='products.turno', verbose_name='Turno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origen', to='ventas.venta', verbose_name='Venta generada')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
                'permissions': [('cancelar_pedido', 'Puede cancelar un pedido y liberar su inventario apartado')],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento (%)')),
                ('estrategia_salida', models.CharField(choices=[('fifo', 'FIFO (primero en entrar, primero en salir)'), ('fefo', 'FEFO (primero en caducar, primero en salir)')], default='fifo', max_length=10, verbose_name='Estrategia de salida')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lista_precio', models.ForeignKey(blank=True, help_text='De qué lista salió el precio_unitario capturado -no se usa para calcularlo, solo se registra para reportes como la comisión por colaborador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.listaprecio', verbose_name='Lista de precio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='products.producto', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalleLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad apartada')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo unitario al momento de apartar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='pedidos.pedidodetalle', verbose_name='Detalle de pedido')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='inventario.lote', verbose_name='Lote de origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de pedido',
                'verbose_name_plural': 'Lotes de pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='pedidos_ped_cliente_06d92d_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['almacen'], name='pedidos_ped_almacen_aea52e_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estatus'], name='pedidos_ped_estatus_1601e2_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['punto_venta'], name='pedidos_punto_venta_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidodetalle',
            index=models.Index(fields=['pedido'], name='pedidos_ped_pedido__88b609_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidodetalle',
            index=models.Index(fields=['producto'], name='pedidos_ped_product_be3007_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='pdd_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='pdd_precio_unitario_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0), ('descuento__lte', 100)), name='pdd_descuento_rango_valido'),
        ),
        migrations.AddIndex(
            model_name='pedidodetallelote',
            index=models.Index(fields=['detalle'], name='pedidos_ped_detalle_f0f609_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidodetallelote',
            index=models.Index(fields=['lote'], name='pedidos_ped_lote_id_58dd5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetallelote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='pdl_cantidad_positiva'),
        ),
    ]
