# Generated by Django 5.2.14 on 2026-08-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_lote_movimiento_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('traspaso', 'Traspaso')], max_length=10, verbose_name='Tipo de movimiento'),
        ),
    ]
