# Generated by Django 5.2.14 on 2026-08-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_almacen_tipo_y_traspaso_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('traspaso', 'Traspaso'), ('devolucion', 'Devolución de cliente')], max_length=10, verbose_name='Tipo de movimiento'),
        ),
    ]
