# Generated by Django 5.2.14 on 2026-09-02 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_retarget_user_fk_to_accounts'),
        ('products', '0017_puntoventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_origen', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad origen')),
                ('cantidad_destino', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad destino')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_conversion_destino', to='products.producto', verbose_name='Producto destino')),
                ('producto_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_conversion_origen', to='products.producto', verbose_name='Producto origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receta de conversión',
                'verbose_name_plural': 'Recetas de conversión',
                'ordering': ['producto_origen__nombre', 'producto_destino__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_origen_convertida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad de origen convertida')),
                ('cantidad_destino_generada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad de destino generada')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor_consumido', models.DecimalField(decimal_places=2, help_text='Costo real (FIFO) del producto origen que salió.', max_digits=12, verbose_name='Valor consumido')),
                ('valor_generado', models.DecimalField(decimal_places=2, help_text='Cantidad destino × costo de catálogo del producto destino.', max_digits=12, verbose_name='Valor generado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversiones', to='products.almacen', verbose_name='Almacén')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversiones', to='inventario.recetaconversion', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Conversión',
                'verbose_name_plural': 'Conversiones',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recetaconversion',
            index=models.Index(fields=['producto_origen'], name='inventario__product_e74b81_idx'),
        ),
        migrations.AddIndex(
            model_name='recetaconversion',
            index=models.Index(fields=['producto_destino'], name='inventario__product_6d5fc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='recetaconversion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_origen__gt', 0)), name='receta_cantidad_origen_positiva'),
        ),
        migrations.AddConstraint(
            model_name='recetaconversion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_destino__gt', 0)), name='receta_cantidad_destino_positiva'),
        ),
        migrations.AddConstraint(
            model_name='recetaconversion',
            constraint=models.UniqueConstraint(fields=('producto_origen', 'producto_destino'), name='receta_unica_por_par_de_productos'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['almacen'], name='inventario__almacen_8ec96b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['receta'], name='inventario__receta__ccb546_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['fecha'], name='inventario__fecha_dbf779_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_origen_convertida__gt', 0)), name='conversion_cantidad_origen_positiva'),
        ),
        migrations.AddConstraint(
            model_name='conversion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_destino_generada__gt', 0)), name='conversion_cantidad_destino_positiva'),
        ),
        migrations.AddConstraint(
            model_name='conversion',
            constraint=models.CheckConstraint(condition=models.Q(('valor_consumido__gte', 0)), name='conversion_valor_consumido_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='conversion',
            constraint=models.CheckConstraint(condition=models.Q(('valor_generado__gte', 0)), name='conversion_valor_generado_no_negativo'),
        ),
    ]
