# Generated by Django 5.2.14 on 2026-09-02 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_recetaconversion_conversion_and_more'),
        ('products', '0017_puntoventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recetaconversion',
            name='limite_diario_origen',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Máximo del producto origen que se puede convertir en un mismo día con esta receta, sumando todas las conversiones de ese día en el mismo almacén (ej. 5 sacos/día, aunque lo normal sea convertir 2). Déjalo vacío si no aplica un límite.', max_digits=12, null=True, verbose_name='Límite diario de origen'),
        ),
        migrations.AddConstraint(
            model_name='recetaconversion',
            constraint=models.CheckConstraint(condition=models.Q(('limite_diario_origen__isnull', True), ('limite_diario_origen__gt', 0), _connector='OR'), name='receta_limite_diario_positivo_o_nulo'),
        ),
    ]
