# Generated by Django 5.2.14 on 2026-09-30 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_recetaconversion_limite_diario_origen_and_more'),
        ('products', '0027_almacen_puntoventa_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsamblePaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad armada')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor_consumido', models.DecimalField(decimal_places=2, help_text='Costo real (FIFO) de los componentes que salieron.', max_digits=12, verbose_name='Valor consumido')),
                ('valor_generado', models.DecimalField(decimal_places=2, help_text='Cantidad armada × costo de catálogo del paquete.', max_digits=12, verbose_name='Valor generado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ensambles_paquete', to='products.almacen', verbose_name='Almacén')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ensambles', to='products.producto', verbose_name='Paquete')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ensamble de paquete',
                'verbose_name_plural': 'Ensambles de paquete',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['almacen'], name='inventario__almacen_e90474_idx'), models.Index(fields=['paquete'], name='inventario__paquete_c83cab_idx'), models.Index(fields=['fecha'], name='inventario__fecha_fe8ff2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ensamble_cantidad_positiva'), models.CheckConstraint(condition=models.Q(('valor_consumido__gte', 0)), name='ensamble_valor_consumido_no_negativo'), models.CheckConstraint(condition=models.Q(('valor_generado__gte', 0)), name='ensamble_valor_generado_no_negativo')],
            },
        ),
    ]
