# Generated by Django 5.2.14 on 2026-10-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_ensamblepaquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('traspaso', 'Traspaso'), ('devolucion', 'Devolución de cliente'), ('pedido', 'Apartado de pedido')], max_length=10, verbose_name='Tipo de movimiento'),
        ),
    ]
