# Generated by Django 5.2.14 on 2026-10-01 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_ordencompra_flete_ordencompra_oc_flete_no_negativo'),
        ('inventario', '0008_alter_movimientoinventario_tipo'),
        ('products', '0029_almacen_tipo_movil'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(choices=[('entrada_ajuste', 'Entrada por ajuste'), ('entrada_sobrante', 'Entrada por sobrante'), ('entrada_regalia', 'Entrada por regalía'), ('entrada_dev_proveedor', 'Entrada por devolución del proveedor'), ('salida_ajuste', 'Salida por ajuste'), ('salida_faltante', 'Salida por faltante'), ('salida_merma', 'Salida por merma'), ('salida_regalia', 'Salida por regalía'), ('salida_dev_proveedor', 'Salida por devolución a proveedor'), ('salida_consumo', 'Salida por consumo de la empresa'), ('salida_dev_movil', 'Salida por devolución del cliente en móvil')], max_length=30, verbose_name='Concepto')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aplicado', 'Aplicado'), ('cancelado', 'Cancelado')], default='borrador', max_length=10, verbose_name='Estado')),
                ('documento_referencia', models.CharField(blank=True, help_text='Factura, nota o remisión a la que corresponde.', max_length=100, verbose_name='Documento de referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aplicación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255, verbose_name='Motivo de cancelación')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen', to='products.almacen', verbose_name='Almacén')),
                ('almacen_destino', models.ForeignKey(blank=True, help_text='Solo para la devolución del cliente en móvil: a dónde regresa la mercancía.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen_recibidos', to='products.almacen', verbose_name='Almacén destino')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('movimiento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_derivados', to='inventario.movimientoalmacen', verbose_name='Movimiento que lo antecede')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen', to='compras.ordencompra', verbose_name='Orden de compra relacionada')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de almacén',
                'verbose_name_plural': 'Movimientos de almacén',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Se fija al aplicar: último costo en entradas, costo promedio de los lotes consumidos en salidas.', max_digits=12, null=True, verbose_name='Costo unitario')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.movimientoalmacen', verbose_name='Movimiento de almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_movimiento_almacen', to='products.producto', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de movimiento de almacén',
                'verbose_name_plural': 'Detalles de movimiento de almacén',
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacenLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.movimientoalmacendetalle', verbose_name='Detalle')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen', to='inventario.lote', verbose_name='Lote afectado')),
                ('lote_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen_destino', to='inventario.lote', verbose_name='Lote generado en destino')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de movimiento de almacén',
                'verbose_name_plural': 'Lotes de movimiento de almacén',
            },
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['concepto'], name='inventario__concept_232049_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['estado'], name='inventario__estado_0ec196_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['fecha'], name='inventario__fecha_9dc6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['almacen'], name='inventario__almacen_650d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacendetalle',
            index=models.Index(fields=['movimiento'], name='inventario__movimie_f3597b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacendetalle',
            index=models.Index(fields=['producto'], name='inventario__product_b530bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoalmacendetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='mad_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimientoalmacendetalle',
            constraint=models.UniqueConstraint(fields=('movimiento', 'producto'), name='mad_producto_unico_por_movimiento'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacenlote',
            index=models.Index(fields=['detalle'], name='inventario__detalle_c12e99_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacenlote',
            index=models.Index(fields=['lote'], name='inventario__lote_id_8ad4fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoalmacenlote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='mal_lote_cantidad_positiva'),
        ),
    ]
