# Generated by Django 5.2.14 on 2026-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_movimiento_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensamblepaquete',
            name='valor_generado',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad armada × costo unitario del lote armado (el costo real de sus componentes).', max_digits=12, verbose_name='Valor generado'),
        ),
    ]
