# Generated by Django 5.2.7 on 2026-04-09 08:07

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una %(model_name)s con este nombre.'}, max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='SKU')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de barras')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio'), ('insumo', 'Insumo')], default='producto', max_length=20, verbose_name='Tipo de producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio de costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio de venta')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Stock mínimo')),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Stock máximo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.categoria', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['sku'], name='products_pr_sku_959014_idx'), models.Index(fields=['nombre'], name='products_pr_nombre_203300_idx'), models.Index(fields=['categoria'], name='products_pr_categor_729bab_idx'), models.Index(fields=['tipo'], name='products_pr_tipo_848a60_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_producto_nombre_ci'), models.CheckConstraint(condition=models.Q(('precio_costo__gte', 0)), name='producto_precio_costo_no_negativo'), models.CheckConstraint(condition=models.Q(('precio_venta__gte', 0)), name='producto_precio_venta_no_negativo'), models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='producto_stock_minimo_no_negativo'), models.CheckConstraint(condition=models.Q(('stock_maximo__gte', 0)), name='producto_stock_maximo_no_negativo'), models.CheckConstraint(condition=models.Q(('stock_maximo__gte', models.F('stock_minimo'))), name='producto_stock_maximo_mayor_igual_minimo')],
            },
        ),
    ]
