# Generated by Django 5.2.7 on 2026-04-23 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_unidadmedida_producto_unidad_medida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la subcategoría')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='products_pr_categor_729bab_idx',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='products.categoria', verbose_name='Categoría padre'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.subcategoria', verbose_name='Subcategoría'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['subcategoria'], name='products_pr_subcate_beacaf_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategoria',
            index=models.Index(fields=['categoria'], name='products_su_categor_51b382_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategoria',
            index=models.Index(fields=['nombre'], name='products_su_nombre_b3acbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='unique_subcategoria_por_categoria'),
        ),
    ]
