# Generated by Django 5.2.14 on 2026-08-17 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_proveedor_producto_proveedor_and_more'),
        ('proveedores', '0001_proveedor_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
