# Generated by Django 5.2.14 on 2026-08-17 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_proveedor_move_to_proveedores_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='tipo',
            field=models.CharField(choices=[('cedis', 'CEDIS'), ('sucursal', 'Sucursal')], default='sucursal', max_length=10, verbose_name='Tipo de almacén'),
        ),
        migrations.AddConstraint(
            model_name='almacen',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'cedis')), fields=('tipo',), name='unico_cedis'),
        ),
    ]
