# Generated by Django 5.2.14 on 2026-08-18 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_almacen_tipo_y_traspaso_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio'), ('insumo', 'Insumo'), ('paquete', 'Paquete/Combo')], default='producto', max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.CreateModel(
            name='PaqueteComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad por paquete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='products.producto', verbose_name='Paquete')),
                ('producto_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_paquetes', to='products.producto', verbose_name='Producto componente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Componente de paquete',
                'verbose_name_plural': 'Componentes de paquete',
                'ordering': ['paquete', 'producto_componente__nombre'],
                'indexes': [models.Index(fields=['paquete'], name='products_pa_paquete_97d40b_idx'), models.Index(fields=['producto_componente'], name='products_pa_product_5a39f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('paquete', 'producto_componente'), name='unico_componente_por_paquete'), models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='paquete_componente_cantidad_positiva')],
            },
        ),
    ]
