# Generated by Django 5.2.14 on 2026-08-18 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_paquete_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='La sucursal que arma este paquete/combo. Solo aplica cuando el tipo es Paquete/Combo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='products.almacen', verbose_name='Sucursal (solo para paquetes)'),
        ),
    ]
