# Generated by Django 5.2.14 on 2026-08-18 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_clave_unidad_prod_serv_sat_initial'),
        ('products', '0010_producto_almacen_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clave_prod_serv_sat',
            field=models.ForeignKey(blank=True, help_text='Requerida para poder facturar este producto (CFDI).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='fiscal.claveprodservsat', verbose_name='Clave de producto o servicio SAT'),
        ),
        migrations.AddField(
            model_name='producto',
            name='clave_unidad_sat',
            field=models.ForeignKey(blank=True, help_text='Requerida para poder facturar este producto (CFDI).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='fiscal.claveunidadsat', verbose_name='Clave de unidad SAT'),
        ),
    ]
