# Generated by Django 5.2.14 on 2026-08-18 05:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_clave_unidad_prod_serv_sat_initial'),
        ('products', '0011_producto_claves_sat'),
        ('proveedores', '0002_descuento_pronto_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aplica_ieps',
            field=models.BooleanField(default=False, verbose_name='Aplica IEPS'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tasa_ieps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Tasa de IEPS (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Solo aplica cuando el IVA es Gravado; varía según el producto (16%, 8% zona fronteriza, etc.).', max_digits=5, verbose_name='Tasa de IVA (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_iva',
            field=models.CharField(choices=[('gravado', 'Gravado'), ('exento', 'Exento')], default='gravado', max_length=10, verbose_name='IVA'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('tasa_iva__gte', 0)), name='producto_tasa_iva_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('tasa_ieps__isnull', True), ('tasa_ieps__gte', 0), _connector='OR'), name='producto_tasa_ieps_no_negativa'),
        ),
    ]
