# Generated by Django 5.2.14 on 2026-08-19 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0008_retarget_user_fk_to_accounts'),
        ('products', '0013_retarget_user_fk_to_accounts'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una %(model_name)s con este nombre.'}, max_length=100, unique=True, verbose_name='Nombre de la lista de precios')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de despliegue')),
            ],
            options={
                'verbose_name': 'Lista de precios',
                'verbose_name_plural': 'Listas de precios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilidad_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Porcentaje de utilidad')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de venta (sin impuesto)')),
            ],
            options={
                'verbose_name': 'Precio de producto',
                'verbose_name_plural': 'Precios de producto',
                'ordering': ['producto__nombre', 'lista_precio__orden'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costeo',
            field=models.CharField(choices=[('manual', 'Manual'), ('ultimo', 'Último costo'), ('promedio', 'Costo promedio')], default='manual', help_text='Cómo se actualiza el costo del producto a partir de las compras.', max_length=10, verbose_name='Método de costeo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='dias_reserva',
            field=models.PositiveIntegerField(default=0, help_text='Días que tarda el proveedor en entregar después del pedido.', verbose_name='Días de reserva'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('peso__isnull', True), ('peso__gte', 0), _connector='OR'), name='producto_peso_no_negativo'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Si se deja vacío, la lista aplica a todas las sucursales; si se asigna, solo aplica a esa sucursal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listas_precio', to='products.almacen', verbose_name='Sucursal exclusiva'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='lista_precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_producto', to='products.listaprecio', verbose_name='Lista de precios'),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='products.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listaprecio',
            index=models.Index(fields=['almacen'], name='products_li_almacen_aa841e_idx'),
        ),
        migrations.AddIndex(
            model_name='productoprecio',
            index=models.Index(fields=['producto'], name='products_pr_product_e03d62_idx'),
        ),
        migrations.AddIndex(
            model_name='productoprecio',
            index=models.Index(fields=['lista_precio'], name='products_pr_lista_p_3ca1cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoprecio',
            constraint=models.UniqueConstraint(fields=('producto', 'lista_precio'), name='unico_precio_por_lista'),
        ),
        migrations.AddConstraint(
            model_name='productoprecio',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gte', 0)), name='producto_precio_venta_lista_no_negativo'),
        ),
    ]
