# Generated by Django 5.2.14 on 2026-08-19 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_listaprecio_productoprecio_producto_codigo_proveedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productoprecio',
            name='unico_precio_por_lista',
        ),
        migrations.RemoveConstraint(
            model_name='productoprecio',
            name='producto_precio_venta_lista_no_negativo',
        ),
        migrations.RemoveIndex(
            model_name='listaprecio',
            name='products_li_almacen_aa841e_idx',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='productoprecio',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Si se deja vacío, el precio aplica a todas las sucursales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precios_producto', to='products.almacen', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='precio_con_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de venta (con impuesto)'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='productoprecio',
            index=models.Index(fields=['almacen'], name='products_pr_almacen_86c38a_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoprecio',
            constraint=models.UniqueConstraint(condition=models.Q(('almacen__isnull', False)), fields=('producto', 'lista_precio', 'almacen'), name='unico_precio_por_lista_y_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='productoprecio',
            constraint=models.UniqueConstraint(condition=models.Q(('almacen__isnull', True)), fields=('producto', 'lista_precio'), name='unico_precio_por_lista_general'),
        ),
        migrations.AddConstraint(
            model_name='productoprecio',
            constraint=models.CheckConstraint(condition=models.Q(('precio_con_impuesto__gte', 0)), name='producto_precio_con_impuesto_no_negativo'),
        ),
    ]
