# Generated by Django 5.2.14 on 2026-08-26 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_linea_producto_linea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('cobro', 'Cobro'), ('pedido', 'Pedido')], default='cobro', max_length=10, verbose_name='Tipo de punto de venta')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='products.almacen', verbose_name='Almacén')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de venta',
                'verbose_name_plural': 'Puntos de venta',
                'ordering': ['almacen', 'codigo'],
                'indexes': [models.Index(fields=['almacen'], name='products_pu_almacen_b6796a_idx')],
                'constraints': [models.UniqueConstraint(fields=('almacen', 'codigo'), name='unico_codigo_por_almacen')],
            },
        ),
    ]
