# Generated by Django 5.2.14 on 2026-09-07 18:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_puntoventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('hora_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Apertura')),
                ('hora_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('estatus', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', editable=False, max_length=10, verbose_name='Estatus')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='products.almacen', verbose_name='Sucursal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', '-hora_apertura'],
                'indexes': [models.Index(fields=['almacen'], name='products_tu_almacen_3528e5_idx'), models.Index(fields=['fecha'], name='products_tu_fecha_aa55b5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estatus', 'abierto')), fields=('almacen',), name='trn_un_turno_abierto_por_almacen')],
            },
        ),
    ]
