# Generated by Django 5.2.14 on 2026-09-08 06:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_turno_punto_venta_finalizar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoStockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Stock mínimo')),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Stock máximo')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_productos', to='products.almacen', verbose_name='Sucursal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sucursales', to='products.producto', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock mínimo/máximo por sucursal',
                'verbose_name_plural': 'Stock mínimo/máximo por sucursal',
                'ordering': ['producto__nombre', 'almacen__nombre'],
                'indexes': [models.Index(fields=['producto'], name='products_pr_product_4d8fff_idx'), models.Index(fields=['almacen'], name='products_pr_almacen_8ba6dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('producto', 'almacen'), name='unico_stock_por_producto_sucursal'), models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='pss_stock_minimo_no_negativo'), models.CheckConstraint(condition=models.Q(('stock_maximo__gte', 0)), name='pss_stock_maximo_no_negativo'), models.CheckConstraint(condition=models.Q(('stock_maximo__gte', models.F('stock_minimo'))), name='pss_stock_maximo_mayor_igual_minimo')],
            },
        ),
    ]
