# Generated by Django 5.2.14 on 2026-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productostocksucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='direccion',
            field=models.CharField(blank=True, help_text='Se muestra en el ticket de venta impreso en esta sucursal.', max_length=255, verbose_name='Dirección'),
        ),
    ]
