# Generated by Django 5.2.14 on 2026-09-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_clase_producto_clase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='impresora_ancho_columnas',
            field=models.PositiveSmallIntegerField(default=40, help_text='Caracteres por línea que soporta la impresora de esta sucursal (40 en las Epson TM-U220 de impacto).', verbose_name='Ancho de la impresora (columnas)'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='impresora_nombre',
            field=models.CharField(blank=True, help_text='Debe coincidir exactamente con el nombre de la impresora tal como quedó agregada en Windows (y como la ve QZ Tray en esa PC de caja).', max_length=100, verbose_name='Nombre de la impresora de tickets'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='imprimir_ticket_automatico',
            field=models.BooleanField(default=False, help_text='Actívalo solo cuando ya se haya probado que QZ Tray y la impresora de esta sucursal funcionan correctamente.', verbose_name='Imprimir ticket automáticamente al cerrar la venta'),
        ),
    ]
