# Generated by Django 5.2.14 on 2026-09-12 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0009_renombrar_forma_pago_17'),
        ('products', '0024_almacen_impresora_ticket'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volumen (m³)'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('volumen__isnull', True), ('volumen__gte', 0), _connector='OR'), name='producto_volumen_no_negativo'),
        ),
    ]
