# Generated by Django 5.2.14 on 2026-10-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_almacen_puntoventa_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventa',
            name='consecutivo_pedido',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Último consecutivo de pedido usado'),
        ),
    ]
