# Generated by Django 5.2.14 on 2026-10-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_puntoventa_consecutivo_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='tipo',
            field=models.CharField(choices=[('cedis', 'CEDIS'), ('sucursal', 'Sucursal'), ('movil', 'Móvil')], default='sucursal', max_length=10, verbose_name='Tipo de almacén'),
        ),
    ]
