# Generated by Django 5.2.14 on 2026-10-02 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_almacen_tipo_movil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='turno',
            name='trn_un_turno_abierto_por_punto_venta',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus', 'abierto')), fields=('punto_venta',), name='trn_un_turno_abierto_por_punto_venta', violation_error_message='Este punto de venta ya tiene un turno abierto.'),
        ),
    ]
