# Generated by Django 5.2.14 on 2026-09-01 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0017_puntoventa'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una %(model_name)s con este nombre.'}, max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('naturaleza', models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable')], default='variable', help_text='Fijo: no depende de cuánto se venda (renta, internet). Variable: depende del nivel de operación.', max_length=10, verbose_name='Naturaleza')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('sucursal', 'Sucursal (venta al público)'), ('proyecto', 'Proyecto / actividad no comercial'), ('administrativo', 'Administración / corporativo'), ('personal', 'Gasto personal de los dueños')], max_length=15, verbose_name='Tipo de centro de costo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('almacen', models.OneToOneField(blank=True, help_text='Obligatorio y único para centros de tipo Sucursal; no aplica a los demás tipos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centro_costo', to='products.almacen', verbose_name='Sucursal (almacén)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Centro de costo',
                'verbose_name_plural': 'Centros de costo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('fecha', models.DateField(verbose_name='Fecha del gasto')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe total')),
                ('facturado', models.BooleanField(default=False, verbose_name='Facturado (con CFDI)')),
                ('referencia_factura', models.CharField(blank=True, help_text='Folio o UUID fiscal, cuando el gasto está facturado.', max_length=50, verbose_name='Referencia de factura')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/comprobantes/', verbose_name='Comprobante')),
                ('es_compartido', models.BooleanField(default=False, help_text='Actívalo cuando el gasto beneficia a más de una sucursal (p. ej. un servicio corporativo) y necesites repartirlo con montos exactos.', verbose_name='Se distribuye entre varias sucursales')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.categoriagasto', verbose_name='Categoría')),
                ('centro_costo', models.ForeignKey(help_text='Quién generó/pagó el gasto. Si es compartido, aquí se registra el centro de origen (p. ej. Administración) y el detalle real por sucursal va en la distribución.', on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.centrocosto', verbose_name='Centro de costo de origen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GastoDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto asignado')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_gasto', to='gastos.centrocosto', verbose_name='Sucursal beneficiada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='gastos.gasto', verbose_name='Gasto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribución de gasto',
                'verbose_name_plural': 'Distribuciones de gasto',
            },
        ),
        migrations.AddIndex(
            model_name='centrocosto',
            index=models.Index(fields=['tipo'], name='gastos_cent_tipo_ef39de_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['centro_costo'], name='gastos_gast_centro__a561a4_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['categoria'], name='gastos_gast_categor_1b564a_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['fecha'], name='gastos_gast_fecha_3f4b13_idx'),
        ),
        migrations.AddConstraint(
            model_name='gasto',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='gto_importe_positivo'),
        ),
        migrations.AddIndex(
            model_name='gastodistribucion',
            index=models.Index(fields=['gasto'], name='gastos_gast_gasto_i_b70f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='gastodistribucion',
            index=models.Index(fields=['centro_costo'], name='gastos_gast_centro__27600b_idx'),
        ),
        migrations.AddConstraint(
            model_name='gastodistribucion',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='gtd_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='gastodistribucion',
            constraint=models.UniqueConstraint(fields=('gasto', 'centro_costo'), name='gtd_unico_por_gasto_y_centro'),
        ),
    ]
