# Generated by Django 5.2.14 on 2026-09-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocosto',
            options={'ordering': ['codigo', 'nombre'], 'verbose_name': 'Centro de costo', 'verbose_name_plural': 'Centros de costo'},
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Identificador corto para reconocerlo rápido en reportes (p. ej. "01" o "SUR"). Opcional.', max_length=20, null=True, unique=True, verbose_name='Código corto'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='responsable',
            field=models.CharField(blank=True, help_text='Quién recibió o autorizó el gasto (nombre libre; no necesariamente un usuario del sistema).', max_length=150, verbose_name='Responsable'),
        ),
    ]
