# Generated by Django 5.2.14 on 2026-09-07 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_categorias_gasto_iniciales'),
        ('products', '0018_turno'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='condicion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado de seguimiento del gasto, independiente de si está facturado. Un gasto Cancelado no cuenta en el reporte de punto de equilibrio.', max_length=10, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='numero',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasto',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referencia interna/administrativa (folio de caja, número de memo, clave de control propia). No es el folio o UUID fiscal -para eso está "Referencia de factura".', max_length=100, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Obligatorio cuando el centro de costo es de tipo Sucursal: el turno abierto de esa sucursal en el que se aplicó el gasto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='products.turno', verbose_name='Turno'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['turno'], name='gastos_gast_turno_i_76fd6a_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['condicion'], name='gastos_gast_condici_fe2c00_idx'),
        ),
    ]
