# Generated by Django 5.2.14 on 2026-09-30 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_gasto_condicion_gasto_numero_gasto_referencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriagasto',
            options={'ordering': ['grupo__orden', 'nombre'], 'verbose_name': 'Concepto de gasto', 'verbose_name_plural': 'Conceptos de gasto'},
        ),
        migrations.AddField(
            model_name='categoriagasto',
            name='criterio',
            field=models.TextField(blank=True, verbose_name='Criterio / no incluir'),
        ),
        migrations.AddField(
            model_name='categoriagasto',
            name='cuenta_contable',
            field=models.CharField(blank=True, help_text='Cuenta del plan de cuentas contable (p. ej. 4101-015-000) a la que se envía este concepto.', max_length=20, verbose_name='Cuenta contable'),
        ),
        migrations.AddField(
            model_name='categoriagasto',
            name='ejemplos',
            field=models.TextField(blank=True, verbose_name='Ejemplos de captura'),
        ),
        migrations.AlterField(
            model_name='categoriagasto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Qué debe registrarse'),
        ),
        migrations.AlterField(
            model_name='categoriagasto',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un concepto de gasto con este nombre.'}, max_length=100, unique=True, verbose_name='Nombre del concepto'),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='tipo',
            field=models.CharField(choices=[('sucursal', 'Sucursal (venta al público)'), ('unidad_negocio', 'Unidad de negocio (ingreso propio, sin mostrador)'), ('proyecto', 'Proyecto / actividad no comercial'), ('administrativo', 'Administración / corporativo'), ('personal', 'Gasto personal de los dueños')], max_length=15, verbose_name='Tipo de centro de costo'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.categoriagasto', verbose_name='Concepto de gasto'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='es_compartido',
            field=models.BooleanField(default=False, help_text='Actívalo cuando el gasto beneficia a más de un centro de costo (p. ej. una factura de gasolina que se reparte entre Transporte, Administración y Personal) y necesites repartirlo con montos exactos.', verbose_name='Se distribuye entre varios centros de costo'),
        ),
        migrations.AlterField(
            model_name='gastodistribucion',
            name='centro_costo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_gasto', to='gastos.centrocosto', verbose_name='Centro de costo beneficiado'),
        ),
        migrations.CreateModel(
            name='GrupoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un %(model_name)s con este nombre.'}, max_length=100, unique=True, verbose_name='Nombre del grupo')),
                ('clasificacion', models.CharField(choices=[('gasto', 'Gasto de operación'), ('inversion', 'Inversión / activo fijo'), ('no_operativo', 'Movimiento no operativo')], default='gasto', help_text='Solo lo clasificado como Gasto de operación cuenta en el reporte de punto de equilibrio.', max_length=15, verbose_name='Clasificación')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de gasto',
                'verbose_name_plural': 'Grupos de gasto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='categoriagasto',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='gastos.grupogasto', verbose_name='Grupo'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una unidad con este nombre.'}, help_text='Cómo se le conoce en la operación (p. ej. "Nissan 2014", "KW 2017", "Montacargas").', max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('vehiculo', 'Vehículo'), ('maquinaria', 'Maquinaria / equipo')], max_length=10, verbose_name='Tipo')),
                ('placas', models.CharField(blank=True, max_length=15, verbose_name='Placas')),
                ('responsable', models.CharField(blank=True, max_length=150, verbose_name='Responsable / chofer')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('centro_costo', models.ForeignKey(blank=True, help_text='A dónde se carga normalmente su gasto. Es solo una referencia: cada gasto elige su centro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='gastos.centrocosto', verbose_name='Centro de costo habitual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo o maquinaria',
                'verbose_name_plural': 'Vehículos y maquinaria',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='vehiculo',
            field=models.ForeignKey(blank=True, help_text='Opcional: la unidad a la que corresponde el gasto (combustible, casetas, refacciones, mantenimiento).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.vehiculo', verbose_name='Vehículo o maquinaria'),
        ),
    ]
