# Generated by Django 5.2.14 on 2026-10-01 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gastos', '0010_permisos_y_ajustes_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAccesoGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nombre', models.CharField(help_text='Copia del nombre al momento del cambio, por si el grupo se renombra o se borra.', max_length=150, verbose_name='Nombre de la capacidad')),
                ('accion', models.CharField(choices=[('otorgada', 'Otorgada'), ('retirada', 'Retirada')], max_length=10, verbose_name='Acción')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group', verbose_name='Capacidad')),
                ('realizado_por', models.ForeignKey(blank=True, help_text='Vacío cuando el cambio se hizo desde el servidor (migración o comando), no desde el sistema.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacora_acceso_gastos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de acceso a Gastos',
                'verbose_name_plural': 'Bitácora de acceso a Gastos',
                'ordering': ['-fecha', '-pk'],
                'indexes': [models.Index(fields=['usuario'], name='gastos_bita_usuario_0ce898_idx'), models.Index(fields=['fecha'], name='gastos_bita_fecha_f75fef_idx')],
            },
        ),
    ]
