# Generated by Django 5.2.14 on 2026-10-02 11:12

import apps.core.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0012_acceso_estricto_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.archivos.RutaAleatoria('gastos/comprobantes'), verbose_name='Comprobante'),
        ),
    ]
