# Generated by Django 5.2.14 on 2026-10-06 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0013_comprobante_ruta_aleatoria'),
        ('products', '0030_turno_mensaje_restriccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='clave_importacion',
            field=models.CharField(blank=True, editable=False, help_text='Hoja y fila del Excel de pólizas de donde salió; evita importar dos veces el mismo vale.', max_length=80, null=True, unique=True, verbose_name='Origen en el Excel'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='factura_caja_anterior',
            field=models.CharField(blank=True, editable=False, help_text='La factura de venta del turno de la que salió el efectivo (columna "Factura donde sale el gasto" del Excel), no la factura del proveedor.', max_length=30, verbose_name='Factura de caja en el sistema anterior'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='importado',
            field=models.BooleanField(default=False, editable=False, verbose_name='Importado del sistema anterior'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='turno_anterior',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Turno en el sistema anterior'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Obligatorio cuando el centro de costo es de tipo Sucursal: el turno abierto de esa sucursal en el que se aplicó el gasto (salvo en los gastos importados del sistema anterior).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='products.turno', verbose_name='Turno'),
        ),
    ]
