# Generated by Django 5.2.14 on 2026-08-17 22:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_proveedor_move_to_proveedores_app'),
        ('proveedores', '0001_proveedor_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_orden', models.DateField(verbose_name='Fecha de orden')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega estimada')),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('parcial', 'Recepción parcial'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='borrador', max_length=15, verbose_name='Estatus')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-fecha_orden', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cantidad recibida')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra', verbose_name='Orden de compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden_compra', to='products.producto', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de orden de compra',
                'verbose_name_plural': 'Detalles de orden de compra',
            },
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor'], name='compras_ord_proveed_1ca32e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estatus'], name='compras_ord_estatus_ebef55_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['fecha_orden'], name='compras_ord_fecha_o_118b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalle',
            index=models.Index(fields=['orden_compra'], name='compras_ord_orden_c_247382_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalle',
            index=models.Index(fields=['producto'], name='compras_ord_product_199539_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ocd_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='ocd_precio_unitario_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_recibida__gte', 0)), name='ocd_cantidad_recibida_no_negativa'),
        ),
    ]
