# Generated by Django 5.2.14 on 2026-08-18 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_orden_compra_initial'),
        ('products', '0008_almacen_tipo_y_traspaso_choice'),
        ('proveedores', '0002_descuento_pronto_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', '% de descuento'), ('precio_fijo', 'Precio promocional fijo')], max_length=15, verbose_name='Tipo de promoción')),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento (%)')),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio promocional')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promociones_proveedor', to='products.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promociones', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promoción de proveedor',
                'verbose_name_plural': 'Promociones de proveedor',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['proveedor', 'producto'], name='compras_pro_proveed_063237_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='compras_pro_fecha_i_ae6b51_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='promo_fecha_fin_no_anterior_inicio')],
            },
        ),
    ]
