# Generated by Django 5.2.14 on 2026-08-18 17:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_promocion_proveedor_initial'),
        ('fiscal', '0007_clave_unidad_prod_serv_sat_initial'),
        ('proveedores', '0002_descuento_pronto_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='documento',
            field=models.CharField(blank=True, help_text='Número de factura o folio de nota de venta del proveedor.', max_length=50, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='es_fiscal',
            field=models.BooleanField(default=False, verbose_name='Es fiscal'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estado_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Estado de pago'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='fiscal.formapago', verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='ieps',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IEPS'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='medio_pago',
            field=models.CharField(choices=[('caja', 'Caja'), ('banco', 'Banco'), ('indefinido', 'Indefinido')], default='indefinido', max_length=15, verbose_name='Medio de pago'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Retención ISR'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='retencion_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Retención IVA'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('iva__gte', 0)), name='oc_iva_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('ieps__gte', 0)), name='oc_ieps_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('retencion_iva__gte', 0)), name='oc_retencion_iva_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('retencion_isr__gte', 0)), name='oc_retencion_isr_no_negativa'),
        ),
    ]
