# Generated by Django 5.2.14 on 2026-08-18 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_retarget_user_fk_to_accounts'),
        ('fiscal', '0008_retarget_user_fk_to_accounts'),
        ('products', '0013_retarget_user_fk_to_accounts'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, help_text='El alta de la compra siempre queda a nombre del CEDIS (ahí está la relación comercial con el proveedor); este campo indica dónde debe impactar físicamente la mercancía: el propio CEDIS, o una sucursal cuando el proveedor entrega directo ahí.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_destino', to='products.almacen', verbose_name='Almacén destino'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['almacen_destino'], name='compras_ord_almacen_7bfb52_idx'),
        ),
    ]
