# Generated by Django 5.2.14 on 2026-08-24 21:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_ordencompra_almacen_destino_and_more'),
        ('products', '0016_linea_producto_linea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompradetalle',
            name='cantidad_merma',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='De lo recibido, cuánto se dio de baja por llegar en mal estado. El proveedor descuenta esta cantidad de lo que factura y cobra.', max_digits=12, verbose_name='Cantidad dañada (no facturable)'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_merma__gte', 0)), name='ocd_cantidad_merma_no_negativa'),
        ),
    ]
