# Generated by Django 5.2.14 on 2026-08-28 16:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_ordencompradetalle_cantidad_merma_and_more'),
        ('fiscal', '0009_renombrar_forma_pago_17'),
        ('products', '0017_puntoventa'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento general que el proveedor aplica sobre el subtotal de la orden.', max_digits=5, verbose_name='Descuento proveedor (%)'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_pct__gte', 0), ('descuento_pct__lte', 100)), name='oc_descuento_pct_rango_valido'),
        ),
    ]
