# Generated by Django 5.2.14 on 2026-08-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_ordencompra_descuento_pct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden de compra', 'verbose_name_plural': 'Órdenes de compra'},
        ),
    ]
