# Generated by Django 5.2.14 on 2026-09-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_ordencompra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='cfdi_uuid',
            field=models.CharField(blank=True, help_text='Folio fiscal del CFDI si esta orden se generó cargando el XML de la factura.', max_length=36, null=True, unique=True, verbose_name='UUID del CFDI'),
        ),
    ]
