# Generated by Django 5.2.14 on 2026-09-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_ordencompra_cfdi_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, help_text='Admite hasta 4 decimales: el valor unitario real de un CFDI a veces trae más precisión de la que se ve impresa (ej. $66.785 se imprime como $66.79), y con solo 2 decimales el importe de la línea no cuadra exacto contra la factura.', max_digits=14, verbose_name='Precio unitario'),
        ),
    ]
