# Generated by Django 5.2.14 on 2026-09-24 05:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_alter_ordencompradetalle_precio_unitario'),
        ('fiscal', '0009_renombrar_forma_pago_17'),
        ('products', '0027_almacen_puntoventa_numero'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='flete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de transporte pagado a un tercero (no al proveedor) para traer esta mercancía. No se suma a total/cuenta por pagar del proveedor; solo se prorratea entre los productos de la orden para reflejar su costo real de entrada al almacén.', max_digits=12, verbose_name='Flete'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('flete__gte', 0)), name='oc_flete_no_negativo'),
        ),
    ]
