# Generated by Django 5.2.14 on 2026-10-01 22:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Q, Subquery


def congelar_descuento_base(apps, schema_editor):
    """Las órdenes ya capturadas toman el % base que hoy tiene su proveedor
    (es lo que ya usaban al calcular su total); las cargadas desde un CFDI
    se quedan en 0, porque su precio ya viene neto. Un solo UPDATE con
    subconsulta, sin recorrer órdenes en Python. Solo escribe en
    OrdenCompra: Proveedor se lee, nunca se modifica."""
    OrdenCompra = apps.get_model("compras", "OrdenCompra")
    Proveedor = apps.get_model("proveedores", "Proveedor")
    OrdenCompra.objects.filter(Q(cfdi_uuid__isnull=True) | Q(cfdi_uuid="")).update(
        descuento_base_pct=Subquery(
            Proveedor.objects.filter(pk=OuterRef("proveedor_id")).values("descuento")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_ordencompra_flete_ordencompra_oc_flete_no_negativo'),
        ('fiscal', '0009_renombrar_forma_pago_17'),
        ('products', '0029_almacen_tipo_movil'),
        ('proveedores', '0003_retarget_user_fk_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='descuento_base_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='El % base del proveedor (Proveedor.descuento) congelado al registrar la orden -o al cambiarle el proveedor-, para que editar después el descuento del proveedor no reescriba órdenes ya capturadas. Siempre 0 en una orden cargada desde un CFDI: su precio ya viene neto.', max_digits=5, verbose_name='Descuento base del proveedor (%)'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_base_pct__gte', 0), ('descuento_base_pct__lte', 100)), name='oc_descuento_base_pct_rango_valido'),
        ),
        # Al final, después de todo ALTER TABLE: en Postgres un ALTER sobre una
        # tabla con UPDATEs pendientes en la misma transacción puede fallar
        # ("pending trigger events").
        migrations.RunPython(congelar_descuento_base, migrations.RunPython.noop),
    ]
